//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakultet2.WCFService.KolegijService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kolegij", Namespace="http://schemas.datacontract.org/2004/07/Fakultet2.WCFService.Models")]
    [System.SerializableAttribute()]
    public partial class Kolegij : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumPocetkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UcionicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumPocetka {
            get {
                return this.DatumPocetkaField;
            }
            set {
                if ((this.DatumPocetkaField.Equals(value) != true)) {
                    this.DatumPocetkaField = value;
                    this.RaisePropertyChanged("DatumPocetka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ucionica {
            get {
                return this.UcionicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UcionicaField, value) != true)) {
                    this.UcionicaField = value;
                    this.RaisePropertyChanged("Ucionica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KolegijService.IKolegijService")]
    public interface IKolegijService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKolegijService/DohvatiKolegije", ReplyAction="http://tempuri.org/IKolegijService/DohvatiKolegijeResponse")]
        Fakultet2.WCFService.KolegijService.Kolegij[] DohvatiKolegije();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKolegijService/DohvatiKolegije", ReplyAction="http://tempuri.org/IKolegijService/DohvatiKolegijeResponse")]
        System.Threading.Tasks.Task<Fakultet2.WCFService.KolegijService.Kolegij[]> DohvatiKolegijeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKolegijService/DohvatiKolegij", ReplyAction="http://tempuri.org/IKolegijService/DohvatiKolegijResponse")]
        Fakultet2.WCFService.KolegijService.Kolegij DohvatiKolegij(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKolegijService/DohvatiKolegij", ReplyAction="http://tempuri.org/IKolegijService/DohvatiKolegijResponse")]
        System.Threading.Tasks.Task<Fakultet2.WCFService.KolegijService.Kolegij> DohvatiKolegijAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKolegijServiceChannel : Fakultet2.WCFService.KolegijService.IKolegijService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KolegijServiceClient : System.ServiceModel.ClientBase<Fakultet2.WCFService.KolegijService.IKolegijService>, Fakultet2.WCFService.KolegijService.IKolegijService {
        
        public KolegijServiceClient() {
        }
        
        public KolegijServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KolegijServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KolegijServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KolegijServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Fakultet2.WCFService.KolegijService.Kolegij[] DohvatiKolegije() {
            return base.Channel.DohvatiKolegije();
        }
        
        public System.Threading.Tasks.Task<Fakultet2.WCFService.KolegijService.Kolegij[]> DohvatiKolegijeAsync() {
            return base.Channel.DohvatiKolegijeAsync();
        }
        
        public Fakultet2.WCFService.KolegijService.Kolegij DohvatiKolegij(int id) {
            return base.Channel.DohvatiKolegij(id);
        }
        
        public System.Threading.Tasks.Task<Fakultet2.WCFService.KolegijService.Kolegij> DohvatiKolegijAsync(int id) {
            return base.Channel.DohvatiKolegijAsync(id);
        }
    }
}
