// <auto-generated />
namespace Fakultet2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbFakultet2Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbFakultet2Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202012071301046_dbFakultet2Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
