//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIFakultet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolegij
    {
        public int id { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Ucionica { get; set; }
    }
}
